// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.AWS.S3TypeProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("FSharp.AWS.S3TypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing FSharp.AWS.S3TypeProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.AWS.S3TypeProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "FSharp.AWS.S3TypeProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing FSharp.AWS.S3TypeProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
